### GET /api/aula { plantilla }
GET http://localhost:1234/api/aula
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzE2ODg4NzgsImV4cCI6MTczMTY5NjA3OH0.1Nmo1BjaZlL7W-8ic-srG-ViSTZOssos9Pz7Udtb-mc
Content-Type: application/json

{
    "plantilla": "f5cacd26-170b-465b-9720-430314945ef7"
}

### GET /api/aula/:aula_cod
GET http://localhost:1234/api/aula/012b8ff9-5d77-411f-8d00-2e396abb04b7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzE2ODg4NzgsImV4cCI6MTczMTY5NjA3OH0.1Nmo1BjaZlL7W-8ic-srG-ViSTZOssos9Pz7Udtb-mc

### POST /api/aula { plantilla, nombre, tipo }
POST http://localhost:1234/api/aula
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzE2ODg4NzgsImV4cCI6MTczMTY5NjA3OH0.1Nmo1BjaZlL7W-8ic-srG-ViSTZOssos9Pz7Udtb-mc
Content-Type: application/json

{
    "plantilla": "f5cacd26-170b-465b-9720-430314945ef7",
    "nombre": "E10",
    "tipo": "Magna"
}

### PATCH /api/aula/:aula_cod { nombre, tipo }  Elimina todos los horarios
PATCH http://localhost:1234/api/aula/e88dca7f-b2e6-4f18-b9be-5307b65198bf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzE2ODg4NzgsImV4cCI6MTczMTY5NjA3OH0.1Nmo1BjaZlL7W-8ic-srG-ViSTZOssos9Pz7Udtb-mc
Content-Type: application/json

{
    "tipo": "Grande"
}

### DELETE /api/aula/:aula_cod { nombre, tipo }  Elimina todos los horarios
DELETE http://localhost:1234/api/aula/1a8fc001-0325-4fe3-a1d0-fb57088a4390
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzE2ODg4NzgsImV4cCI6MTczMTY5NjA3OH0.1Nmo1BjaZlL7W-8ic-srG-ViSTZOssos9Pz7Udtb-mc