### login
POST http://localhost:1234/api/auth/login
content-type: application/json

{
    "username": "lamux04",
    "password": "1234"
}

### login
POST http://localhost:1234/api/auth/login
content-type: application/json

{
    "username": "Mascayicle",
    "password": "1234"
}

### register
POST http://localhost:1234/api/auth/register
content-type: application/json

{
    "username": "lamux04",
    "password": "1234"
}

### register
POST http://localhost:1234/api/auth/register
content-type: application/json

{
    "username": "Mascayicle",
    "password": "1234"
}


### delete
DELETE http://localhost:1234/api/auth/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbXV4MDQiLCJpYXQiOjE3MzEwMTEwMTUsImV4cCI6MTczMTAxODIxNX0.rn_dGxWV35XjZGQImjbRRGllHUIzaOcQ1CTaEP14RRk
