### GET /api/horario
GET http://localhost:1234/api/horario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzIwMDk4NzQsImV4cCI6MTczMjAxNzA3NH0.u8tApxW3ewjEJoFt6qRT0wGZ1WkZ01fIQEDKmJHMgaQ

### GET /api/horario/:horar_cod
GET http://localhost:1234/api/horario/cfd6a8f7-a385-11ef-951a-cecd02c24f20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzIwMDk4NzQsImV4cCI6MTczMjAxNzA3NH0.u8tApxW3ewjEJoFt6qRT0wGZ1WkZ01fIQEDKmJHMgaQ

### DELETE /api/horario/:horar_cod
DELETE http://localhost:1234/api/horario/e23fc302-a382-11ef-951a-cecd02c24f20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzE2OTY2NjEsImV4cCI6MTczMTcwMzg2MX0.bEAEP3Crp2uaejQZY0mu5dM6b1jawyGCK6d9IlAePCw

### POST /api/horario/visualizar  { horario }
POST http://localhost:1234/api/horario/visualizar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzE2OTY2NjEsImV4cCI6MTczMTcwMzg2MX0.bEAEP3Crp2uaejQZY0mu5dM6b1jawyGCK6d9IlAePCw
Content-Type: application/json

{
    "horario": "cfd6a8f7-a385-11ef-951a-cecd02c24f20"
}