### GET /api/horario
GET http://localhost:1234/api/horario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMDEiLCJpYXQiOjE3MzM1ODU4OTIsImV4cCI6MTczMzU5MzA5Mn0.2pdYGE7oXuHLyDIzvlNQ2WHvpVZ6zSlfp_fnwBh-L9M

### GET /api/horario/:horar_cod
GET https://www.sched4all.site/api/horario/6d164848-14f0-4d9b-9d03-11788c4e6e9a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzM5MTQxMzEsImV4cCI6MTczMzkyMTMzMX0.sSr1RQkova1s8QXqtMcV7PZmnauFWpCSRgIgoQaHusY

### DELETE /api/horario/:horar_cod
DELETE http://localhost:1234/api/horario/e23fc302-a382-11ef-951a-cecd02c24f20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzE2OTY2NjEsImV4cCI6MTczMTcwMzg2MX0.bEAEP3Crp2uaejQZY0mu5dM6b1jawyGCK6d9IlAePCw

### POST /api/horario/visualizar  { horario }
POST http://localhost:1234/api/horario/visualizar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMDEiLCJpYXQiOjE3MzM1ODYwOTYsImV4cCI6MTczMzU5MzI5Nn0.tKKV7opZfQJfNpLOkO37JpQxAU5pb_QmcStdtyCKCd8
Content-Type: application/json

{
    "horario": "cfd6a8f7-a385-11ef-951a-cecd02c24f20"
}

### POST /api/horario/  { plantilla, nombre }
POST http://localhost:1234/api/horario/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2NheWljbGUiLCJpYXQiOjE3MzM1ODcyODQsImV4cCI6MTczMzU5NDQ4NH0.NBTkJwoNpxICk4ZngNzsr7TRIYRGm6AM4i44MEEdmeA
Content-Type: application/json

{
    "plantilla": "f5cacd26-170b-465b-9720-430314945ef7",
    "nombre": "Horario de prueba"
}